# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        default: 'warning'

jobs:
  build:
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
#         python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - uses: actions/checkout@master
#    - name: Install ubuntu deps
#      run: |
#        sudo apt-get update
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#The below is disabled pending https://github.com/sanskrit-coders/jyotisha/runs/1142973750
    - name: Build package
      run: |
        python -m pip install .
        pip install setuptools wheel twine
        python setup.py bdist_wheel
    - name: Build test
      run: |
        python -c "import chandas"
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Upload package
      if: ${{ github.event_name != 'pull_request'}}
      with:
        skip-existing: true
      uses: pypa/gh-action-pypi-publish@release/v1
